config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "people#home"
  get "yuka", to: "people#yuka"
  get "radek", to: "people#radek"
  get "maya", to: "people#maya"
  get "lisa", to: "people#lisa"
  get "contact", to: "people#contact"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def home
    @members = ["yuka", "radek", "maya", "lisa"]
  end
  def yuka
  end
  def radek
  end
  def maya
  end
  def lisa
  end
  def contact
    @members = ["yuka", "radek", "maya", "lisa"]
     if params[:member]
      @members = @members.select { |member| member.start_with?(params[:member]) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Family</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous" >
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>TYSZKIEWICZ FAMILY 😘</h1>

    <%= yield %>

    <h3>This page is done with 💖</h3>
  </body>
</html>

app/views/people/contact.html.erb
<div class="container">
<h2>Who do you want to contact?</h2>

<form action="/contact" method="get">
  <input type="text" name="member" value="<%= params[:member] %>" placeholder="Who are you looking for?">
  <input type="submit">
</form>

<ol>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

<p>We like receiving emails 📧</p>

<%= link_to "Back to home", root_path, :class => "btn btn-primary" %>
</div>

app/views/people/home.html.erb
<div class="container">

<h1>This is our family 👨‍👩‍👧‍👧</h1>

<ul>
  <li><%= link_to "Meet Yuka", yuka_path, :class => "btn btn-info" %></li>
  <li> <%= link_to "Meet Radek", radek_path, :class => "btn btn-info" %></li>
  <li><%= link_to "Meet Maya", maya_path, :class => "btn btn-info" %></li>
  <li><%= link_to "Meet Lisa", lisa_path, :class => "btn btn-info" %></li>
</ul>
  <p><%= link_to "Contact us", contact_path, :class => "btn btn-primary" %></p>
</div>

app/views/people/lisa.html.erb
<div class="container">
<h1>This is Lisa 👧🏻</h1>

<%= link_to "Back to home", root_path, :class => "btn btn-primary" %>
</div>

app/views/people/maya.html.erb
<div class="container">
<h1>This is Maya 👧🏻</h1>

<%= link_to "Back to home", root_path, :class => "btn btn-primary" %>
</div>

app/views/people/radek.html.erb
<div class="container">
<h1>This is Radek 👱🏻‍♂️</h1>

<%= link_to "Back to home", root_path, :class => "btn btn-primary" %>
</div>

app/views/people/yuka.html.erb
<div class="container">
<h1>This is Yuka 👩🏻</h1>
<%= link_to "Back to home", root_path, :class => "btn btn-primary" %>
</div>